In [1]:
import cv2
import numpy as np

image = cv2.imread('Images/house.jpg')
image_original = image.copy()
cv2.imshow('Original Image', image_original)
cv2.waitKey()

# GrayScale and binarization.
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)

contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)

# Iterate through each contour and compute the bounding rectangle.
for c in contours:
    x,y,w,h = cv2.boundingRect(c)
    cv2.rectangle(image_original, (x,y), (x+w, y+h), (0,0,255), 2)
    cv2.imshow('Bounding rectangle', image_original)

cv2.waitKey()

# Iterate through each contour and computer the approx contour.
for c in contours:
    # Calculate accuracy as a percent of the contour perimeter.
    accuracy = 0.03 * cv2.arcLength(c,True)
    approx = cv2.approxPolyDP(c, accuracy, True)
    cv2.drawContours(image, [approx], 0, (0, 255, 0), 2)
    cv2.imshow('Approx poly DP', image)

cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
image = cv2.imread('Images/hand.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

cv2.imshow('Original Image', image)
cv2.waitKey()

ret, thresh = cv2.threshold(gray, 176, 255, 0)

contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)

# Sort Contors by area and then remove the largest frame contour.
# As the last contour is for the whole image, because of the white backgroud.
n = len(contours) - 1
contours = sorted(contours, key=cv2.contourArea, reverse=False)[:n]

# Iterate through contours and draw the convex hull.
for c in contours:
    hull = cv2.convexHull(c)
    print('Hull')
    print(hull)
    cv2.drawContours(image, [hull], 0, (0,255,0), 2)

cv2.imshow('Convex Hull', image)
cv2.waitKey()
cv2.destroyAllWindows()

Hull
[[[234  38]]

 [[308  82]]

 [[313  87]]

 [[379 169]]

 [[381 172]]

 [[383 177]]

 [[383 183]]

 [[309 414]]

 [[304 419]]

 [[296 423]]

 [[291 425]]

 [[280 429]]

 [[274 431]]

 [[253 437]]

 [[245 439]]

 [[228 443]]

 [[208 447]]

 [[196 449]]

 [[189 449]]

 [[188 448]]

 [[ 98 354]]

 [[ 28 258]]

 [[ 28 253]]

 [[129  84]]

 [[133  80]]

 [[136  78]]

 [[229  38]]]
Hull
[[[227  35]]

 [[235  35]]

 [[239  37]]

 [[309  79]]

 [[312  81]]

 [[314  83]]

 [[384 170]]

 [[386 175]]

 [[386 185]]

 [[312 415]]

 [[310 418]]

 [[308 420]]

 [[305 422]]

 [[293 428]]

 [[288 430]]

 [[276 434]]

 [[255 440]]

 [[239 444]]

 [[221 448]]

 [[211 450]]

 [[199 452]]

 [[187 452]]

 [[185 450]]

 [[ 93 353]]

 [[ 25 260]]

 [[ 25 252]]

 [[125  84]]

 [[134  75]]]
